### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by sendudesign** [niivu/niivu#1]
Can I ask you to create a theme? All you need to do is simply change a few colors in your existing theme. I will pay you

**Comment by jmnaleef** [comment]
I'm  J M Naleef a deviantart member. I use your works and give credits to you. But my last 2 post was taken down as copyright violation. Sir was it you complainted. I don't use for commercial purpose or republish. I'm a growing little guy and it has taken ages from small country Sri Lanka. If one more copyright problem occurs, My whole builtup in 17years on deviantart will be vanished for ever. Please if it's you please tell me what wrong I have done ..so I can correct my self. I found noway to contact you except here. Sorry to trouble you here. How do I contact you. Please reply.

**Comment by jmnaleef** [comment]
my mail is jmnaleef@gmail.com

**Comment by jmnaleef** [comment]
![image](https://github.com/user-attachments/assets/7c0fae81-4065-4995-9ecf-499b5122fd9d)
